# Generated by Django 2.2 on 2019-04-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_state', models.CharField(blank=True, choices=[('r', 'Ready to play'), ('p', 'In progress'), ('w', 'Won'), ('l', 'Lost')], default='r', max_length=1)),
            ],
        ),
    ]
